/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false` (hash: 3dca522fde77d58eb5ebcfb1bee1d9aa)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	OWNER_EMAIL: "nicolajbach12@gmail.com";
	REQUIRE_CLOUDFLARE_ACCESS: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OWNER_EMAIL" | "REQUIRE_CLOUDFLARE_ACCESS">> {}
}
