/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv --include-runtime false` (hash: b125a13678e394f784d272d32c4ff620)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	OWNER_EMAIL: "nicolajbach12@gmail.com";
	REQUIRE_CLOUDFLARE_ACCESS: "true";
	ACCESS_TEAM_DOMAIN: "https://boholts-familie.cloudflareaccess.com";
	ACCESS_AUD: "f905646fe1311a4085083b9f1cde31e862a0bf15cf0942a8a7a2efbcdf3ea660";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OWNER_EMAIL" | "REQUIRE_CLOUDFLARE_ACCESS" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
